name: suray_minipos
description: "Proyecto de venta movil de servicio de carga y transporte de pasajeros"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  intl: ^0.18.1
  shared_preferences: ^2.2.0
  provider: ^6.0.5
  pdf: ^3.10.4
  printing: ^5.11.0
  path_provider: ^2.1.5
  flutter_launcher_icons: ^0.13.1
  sqflite: ^2.3.0
  path: ^1.9.0
  crypto: ^3.0.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logocolorminipos.png"  # Usamos la imagen existente
  min_sdk_android: 21  # Nivel de API mínimo para Android
  adaptive_icon_background: "#FFFFFF"  # Color de fondo para íconos adaptativos (Android)
  adaptive_icon_foreground: "assets/logocolorminipos.png"  # Usamos la misma imagen como foreground

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/headTicket.png
    - assets/endTicket.png
    - assets/logobkwt.png
    - assets/tijera.png
    - assets/logocolor.png
    - assets/logocolorminipos.png